### ISSUE TITLE
timedctl not storing the authtoken in my keyring anymore

### ISSUE THREAD

**Issue by pree** [adfinis/timedctl#106]
After the upgrade to 5.9.1 timedctl is reauthenticating with the SSO for every command.
I've noticed, that the token is not updated / saved anymore in my keyring (I'm using `kwalletd5`, but also tried with `gnome-keyring`).

Not sure if it's possible to create some debug output to investigate this further.

**Comment by gianklug** [comment]
Hey @pree, this is related to libtimed, what version are you on there?

**Comment by pree** [comment]
@gianklug python-libtimed: `0.6.2.r1.ge3a31e8-1`, timedctl: `5.9.1.r1.gb97d1ff-1`

**Comment by gianklug** [comment]
I've identified the cause, we committed testing code to main after the SSO broke ^^' 

Building new fixed versions now.

**Comment by gianklug** [comment]
https://github.com/adfinis/timedctl/releases/tag/v5.9.2

**Comment by pree** [comment]
Sadly, this didn't fix it. It now requires the keyring to run again, but doesn't save the token into the keyring.
Executing `timedctl force-renew` results in the following error:
```
Error: 400 Bad Request

{"error":"invalid_grant","error_description":"Code not valid"}
Error: ERR_NO_TOKEN_RENEWAL_FAILED
```

**Comment by gianklug** [comment]
Yeah, small oversight there :facepalm: 

Fix is building rn and should be available in about 5 minutes.

**Comment by gianklug** [comment]
https://github.com/adfinis/timedctl/releases/tag/v5.9.3

**Comment by pree** [comment]
Thanks, it's not reauthenticating on every request & `force-renew` is also working!
